# Generated by Django 5.0.1 on 2024-02-09 16:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ExpenseTracker', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expenseticket',
            name='date',
        ),
        migrations.RemoveField(
            model_name='incometicket',
            name='date',
        ),
        migrations.AddField(
            model_name='expenseticket',
            name='day',
            field=models.DateField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='expenseticket',
            name='month',
            field=models.DateField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='expenseticket',
            name='year',
            field=models.DateField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='incometicket',
            name='day',
            field=models.DateField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='incometicket',
            name='month',
            field=models.DateField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='incometicket',
            name='year',
            field=models.DateField(default=datetime.datetime.now),
        ),
    ]
