# Generated by Django 5.0.1 on 2024-02-09 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ExpenseTracker', '0002_remove_expenseticket_date_remove_incometicket_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incometicket',
            name='day',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='incometicket',
            name='month',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='incometicket',
            name='year',
            field=models.IntegerField(default=0),
        ),
    ]
