# Generated by Django 5.0.1 on 2024-02-09 16:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ExpenseTracker', '0003_alter_incometicket_day_alter_incometicket_month_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expenseticket',
            name='day',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='expenseticket',
            name='month',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='expenseticket',
            name='year',
            field=models.IntegerField(default=0),
        ),
    ]
