# Generated by Django 5.0.1 on 2024-02-09 20:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ExpenseTracker', '0002_remove_expenseticket_date_remove_incometicket_date_and_more.py'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expenseticket',
            name='day',
        ),
        migrations.RemoveField(
            model_name='expenseticket',
            name='month',
        ),
        migrations.RemoveField(
            model_name='expenseticket',
            name='year',
        ),
        migrations.RemoveField(
            model_name='incometicket',
            name='day',
        ),
        migrations.RemoveField(
            model_name='incometicket',
            name='month',
        ),
        migrations.RemoveField(
            model_name='incometicket',
            name='year',
        ),
    ]
